version: 2.1
jobs:        
  - notify:
      docker:
      - image: 'cimg/base:stable'
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD  # context / project UI env-var reference
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*BUILD SUCCESS*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
workflows:
  circleci-jmeter_and_notify-workflow:
    jobs:
      - notify
 


