# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  slack: circleci/slack@4.1
  email: cinotify/email@1.2.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  circleci-jmeter:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: akshayaclops/jmeter:latest
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Make Results Directory
          command: mkdir results
      - run:
          name: "Run tests"
          command: "jmeter -n -t sampleTest.jmx -l results/runResults.csv -e -o results"
      - store_artifacts:
          path: results
  notify:
    docker:
      - image: 'cimg/base:stable'
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD  # context / project UI env-var reference
    steps:
      - slack/notify:
          channel: devops
          event: fail
          custom: |
            {
                        	"text": "CircleCI job failed.",
                        	"blocks": [
                        		{
                        			"type": "header",
                        			"text": {
                        				"type": "plain_text",
                        				"text": "Job Failed. :red_circle:",
                        				"emoji": true
                        			}
                        		},
                        		{
                        			"type": "section",
                        			"fields": [
                        				{
                        					"type": "mrkdwn",
                        					"text": "*Job*: ${CIRCLE_JOB}"
                        				}
                        			]
                        		},
                        		{
                        			"type": "section",
                        			"fields": [
                        				{
                        					"type": "mrkdwn",
                        					"text": "*Project*: $CIRCLE_PROJECT_REPONAME"
                        				},
                        				{
                        					"type": "mrkdwn",
                        					"text": "*Branch*: $CIRCLE_BRANCH"
                        				},
                        				{
                        					"type": "mrkdwn",
                        					"text": "*Author*: $CIRCLE_USERNAME"
                        				}
                        			],
                        			"accessory": {
                        				"type": "image",
                        				"image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
                        				"alt_text": "CircleCI logo"
                        			}
                        		},
                        		{
                        			"type": "section",
                        			"fields": [
                        				{
                        					"type": "mrkdwn",
                        					"text": "*Mentions*: $SLACK_PARAM_MENTIONS"
                        				}
                        			]
                        		},
                        		{
                        			"type": "actions",
                        			"elements": [
                        				{
                        					"type": "button",
                        					"text": {
                        						"type": "plain_text",
                        						"text": "View Job"
                        					},
                        					"url": "${CIRCLE_BUILD_URL}"
                        				}
                        			]
                        		}
                        	]
                        }

      - slack/notify:
          channel: devops
          event: pass
          custom: |
            {
                        	"text": "CircleCI job succeeded!",
                        	"blocks": [
                        		{
                        			"type": "header",
                        			"text": {
                        				"type": "plain_text",
                        				"text": "Job Succeeded. :white_check_mark:",
                        				"emoji": true
                        			}
                        		},
                        		{
                        			"type": "section",
                        			"fields": [
                        				{
                        					"type": "mrkdwn",
                        					"text": "*Job*: ${CIRCLE_JOB}"
                        				}
                        			]
                        		},
                        		{
                        			"type": "section",
                        			"fields": [
                        				{
                        					"type": "mrkdwn",
                        					"text": "*Project*: $CIRCLE_PROJECT_REPONAME"
                        				},
                        				{
                        					"type": "mrkdwn",
                        					"text": "*Branch*: $CIRCLE_BRANCH"
                        				},
                        				{
                        					"type": "mrkdwn",
                        					"text": "*Commit*: $CIRCLE_SHA1"
                        				},
                        				{
                        					"type": "mrkdwn",
                        					"text": "*Author*: $CIRCLE_USERNAME"
                        				}
                        			],
                        			"accessory": {
                        				"type": "image",
                        				"image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
                        				"alt_text": "CircleCI logo"
                        			}
                        		},
                        		{
                        			"type": "section",
                        			"fields": [
                        				{
                        					"type": "mrkdwn",
                        					"text": "*Mentions*: $SLACK_PARAM_MENTIONS"
                        				}
                        			]
                        		},
                        		{
                        			"type": "actions",
                        			"elements": [
                        				{
                        					"type": "button",
                        					"text": {
                        						"type": "plain_text",
                        						"text": "View Job"
                        					},
                        					"url": "${CIRCLE_BUILD_URL}"
                        				}
                        			]
                        		}
                        	]
                        }
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  circleci-jmeter-workflow:
    jobs:
      - circleci-jmeter
  send-notification:
    jobs:
      - notify:
          context: slack-secrets
          
  example-workflow:
    jobs:
      - email/send:
        name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: akshaya.p@cloudifyops.com
          # Required sender full name (address can be skipped):
          from: username # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Build zap job completed successfully!
          # Optional HTML body read from file:
          # html_body: file://README.html
          # Optional carbon copy recipients:
          # cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients:
          # bcc: r2d2@example.com,hansolo@example.com
          # Optional recipient of the email response:
          # reply_to: luke@example.com
          # Optional Message ID this message is replying to:
          # in_reply_to: <random-luke@example.com>
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          attachments: report_html.html
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: low

          
 


