
version: 2.1
orbs:
  slack: circleci/slack@4.1
jobs:
  circleci-jmeter:
    docker:
      - image: akshayaclops/jmeter:latest
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Make Results Directory
          command: mkdir results
      - run:
          name: "Run tests"
          command: "jmeter -n -t sampleTest.jmx -l results/runResults.csv -e -o results"
      - store_artifacts:
          path: results
  deploy_and_notify:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run deploy
      - slack/notify:
          channel: devops
          event: pass
          template: success_tagged_deploy_1

workflows:
  circleci-jmeter-workflow:
    jobs:
      - circleci-jmeter
  deploy_and_notify:
    jobs:
      - deploy:
          context:
            - slack-secrets
